#!/usr/bin/ruby

require 'RightAPI'
require 'crack'

api = RightAPI.new
params = { "credential[name]" => "RC: LAST_TEST", "credential[description]" => "rctester" , "credential[value]" => "test"}


total=0
running=0
off=0

def	countXML(data, base, item)
	@base=base
	@item=item
	@data=data
	@total=0
	@xml=Crack::XML.parse(@data)
	@xml[@base].each { | server | 
		server[@item].each { | x| 
			@total +=1
		}
	}
	@total
end

ebsvolumes = countXML(api.ebs_show("all"),"ec2_ebs_volumes", "aws_id")
puts "Total EBS Volumes: #{ebsvolumes}"

deployments = countXML(api.deployments_show("all"), "deployments", "nickname")
puts "Total Deployments: #{deployments}"

data = api.server_show("all")
servers = countXML(data, "servers", "nickname")
puts "Total Servers: #{servers}"


#puts xml.inspect
exit



xml = Crack::XML.parse(api.deployments_show_all)
d=0
s=0
puts "digraph Deployments { "
xml['deployments'].each { | deployment |
d+=1
deploy=deployment['nickname']
	deployment['servers'].each { | server | 
		puts "\"#{deploy}\" -> \"#{server['nickname']}\";"
		s+=1
	}
}
puts "}"

